### ISSUE TITLE
Sequelize

### ISSUE THREAD

**Issue by FullOfOrange** [orehonyah/se2019_1#6]
ORM이라는 것이 있습니다. 모델을 정의하고 사용한다면, 직접 Raw query를 사용할 필요가 없습니다. (애당초 로직에 쿼리문이 들어가는 것은 좋지 않습니다.)

이를 제거하기 위해 Sequelize 라는 모델을 사용해 보는 것을 추천해드립니다.

**Comment by jinwook1240** [comment]
확인해보겠습니다

**Comment by jinwook1240** [comment]
사용해보고 싶긴 한데 나중에 배워서 써야할듯합니다.
과목 특성상 단계를 밟아가며 만들어야 되네요
